### ISSUE TITLE
loadConvergenceData

### ISSUE THREAD

**Issue by Donovan-chan** [adeschen/methylInheritance#17]
Trying to load convergence data to get data.frame with p-values and then plot.  However, I get an error stating: Error in seq.default(by, nbFiles, by) : wrong sign in 'by' argument

Currently to get seqFiles code (?):
filesInDir <- list.files(path = paste0(analysisResultsDir, toupper(type), "/"), pattern = "[[:digit:]].RDS", all.files = FALSE, full.names = TRUE, recursive = FALSE, ignore.case = FALSE, include.dirs = FALSE, no.. = FALSE) 

nbFiles <- length(filesInDir) 
 
seqFiles <- unique(c(seq(by, nbFiles, by), nbFiles)) 

I believe the code to get list.files should be : 

list.files(path = paste0(permutationResultsDir, "/", toupper(type)), pattern ="[[:digit:]].RDS", all.files = FALSE,full.names = TRUE, recursive = FALSE,ignore.case = FALSE, include.dirs = FALSE, no.. = FALSE)

(since we are counting the number of permutations done, should be go to permutation folder (and not analysis).  Placement of "/" in wrong positions, since directory for permuations is: Permu_folder/type/TYPE_permutation_1/RDS )

attempting to run the "corrected" list.files, returns a list of all the permuation files that were performed

**Comment by adeschen** [comment]
Hi,

Have you used different directories for permutation and observation results? If so, there is a bug in the code causing the error "seq.default(by, nbFiles, by) : wrong sign in 'by' argument".

Otherwise,  the error "seq.default(by, nbFiles, by) : wrong sign in 'by' argument" can also be generated when the "by" argument is larger than the number of permutations in the permutation directory.  

I will push a correction to the bug.

Best,
Astrid

**Comment by Donovan-chan** [comment]
Hi Astrid,
  I hope you are well.  Not sure if you remember me, but I work with Dr. Jacquetta Trasler, and was consulted when you were in the lab of Arnaud Droit, when creating the methylInheritance package.  I've been using the package to look at inheritance in a mouse model exposed to folic acid in utero and adult life (F1).  We have an F2 and F3 that are produced, the latter being the only generation not actually exposed/produced by exposed germ cell.

 The observational analysis (single run of methylKit) are stored in one directory, while the permutations are stored in a separate directory.  I've only done a total of 100 permutations, since there is only a few sites that were found to be inherited between generations (one site from F1 to F3).  I wanted to run the convergence to see if I should do more permutations.
  For the "by" argument, I chose "1" or "2" and still does not work (since there were 100 permutations).

  I tried running just the "modified" script that I wrote in GitHub (i.e. using the permutation directory and moving the "/") by just typing it out and it does provide a list of the permutations I ran. This list was saved (filesInDir) and provided the correct # permutations (lenght(filesInDir) and the specific sequence generations ( seqFiles <- unique(c(seq(by, nbFiles, by), nbFiles))_ in the further steps in the(i.e. postion 1, by 1 = 1,2,3,...;  postion2, by 2 = 2,4,6,...).


Donovan

**Comment by adeschen** [comment]
Hi Donavan,

I am doing well and I do remember you. 

I am currently working on fixing the bug related to using different directories for observation and permutation. The correction should be pushed today.

However, I quick fix that you can try with the unmodified code is to copy the observation file into the permutation directory and use the same directory in the loadConvergenceData() method. 

Technically, you don't need to add the "/"  between the "permutationResultsDir" and " toupper(type)" in the following code:

`    

    filesInDir <- list.files(path = paste0(permutationResultsDir, toupper(type),
                        "/"), pattern = "[[:digit:]].RDS", all.files = FALSE,
                        full.names = TRUE, recursive = FALSE,
                        ignore.case = FALSE, include.dirs = FALSE, no.. = FALSE)

`

As the "/" is already added at the beginning of the function:

`

    if (substr(permutationResultsDir, nchar(permutationResultsDir),
                nchar(permutationResultsDir)) != "/") {
        permutationResultsDir <- paste0(permutationResultsDir, "/")
    }

`

Best,
Astrid

**Comment by Donovan-chan** [comment]
Hi Astrid,
  Glad you are doing well.  I don't normally work with R...still just a beginner in programming...use mainly bash, but slowly learning.

  I will try what you suggested, but I think you mean to place the permutations into the observation directory (since in the original code it points to the  analysisResultsDir)?  The list generatted would only include the permutations and NOT the the "observation" result, since it doesn't fit the pattern of [[:digit:]].RDS ? (ie. SITES_permutation_###.RDS vs. SITES_observed_results.RDS)


________________________________

**Comment by adeschen** [comment]
Hi Donavan,

As long as you use the same directory path for  both _analysisResultsDir_ and _permutationResultsDir_ arguments in the `loadConvergenceData(analysisResultsDir=PATH, permutationResultsDir=PATH, ...)` is should work. 

Coping the observation file to the permutation directory or copying the permutation files to the observation directory should give the same result.


Best, 
Astrid

**Comment by adeschen** [comment]
Hi Donavan,

I have commit the fix to Bioconductor. The corrected version of the package should be available in Bioconductor development version in a few days.

Meanwhile, the package can be downloaded using _devtools_ package:

`

     library(devtools)

     devtools::install_github('adeschen/methylInheritance')

`

A test that shows the corrected code is working:

`
 
    library(methylInheritance)

     data(samplesForTransgenerationalAnalysis)

     runPermutation(methylKitData = samplesForTransgenerationalAnalysis,
         outputDir="./test_permutations", runObservationAnalysis=FALSE, type="sites", nbrPermutations=5, vSeed=221)
	
     runObservation(methylKitData = samplesForTransgenerationalAnalysis,
         outputDir="./test_observation", type="sites", vSeed=221)

     results <- loadConvergenceData(analysisResultsDir="./test_observation",
         permutationResultsDir="./test_permutations", type="sites", inter="i2", position=1, by=1)

`

Can you confirm that it is working for you?

Thanks,
Astrid

**Comment by Donovan-chan** [comment]
Hi Astrid,
  Thanks for working on this.
  I ran the test on my laptop and seems to work fine, producing a data.frame with the correct information to plot the convergence graph.

  Thanks again for you help and updating

Donovan Chan, PhD
Research Associate

Research Institute of the McGill University Health Centre
Childhood Health and Human Development (CHHD) Program
Dr. Jacquetta Trasler's laboratory
1001 boul Décarie
Site Glen Block E, ES1.4380
Montreal, QC H4A 3J1


________________________________

**Comment by adeschen** [comment]
Hi Donavan,

I am glad I could help. I will close the issue.

If you have any other problem/issue/question, don't hesitate to contact me.

Best,
Astrid
